name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7, 3.8]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: python -m pip install pytest pytest-cov pybind11 numpy pandas scikit-learn lightgbm interpret

    - name: Install dependency for lightgbm
      if: matrix.os == 'macos-latest'
      run: brew install libomp

    - name: Install package
      run: python -m pip install -e .

    - name: Generate coverage report
      run: pytest --cov=./ --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true