name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: python -m pip install pytest pytest-cov pybind11 numpy pandas scikit-learn lightgbm # interpret

    - name: Install dependency for lightgbm
      if: matrix.os == 'macos-latest'
      run: brew install libomp

    - name: Install package
      run: python -m pip install -e .

    - name: Generate coverage report
      run: pytest --cov=./ --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        # path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
  
  quality-control:
    name: Quality Control
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter` 
          fetch-depth: 0

      # linting
      - name: Lint Code Base
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CodeQL Init
        uses: github/codeql-action/init@v1
        with:
          languages: python

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: CodeQL Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v1